### ISSUE TITLE
Bitnami redis not running

### ISSUE THREAD

**Issue by mosdraev** [bitnami/bitnami-docker-redis#89]
**Description**

I'm trying to use redis container for my local project but bitnami/redis containers gives a permission error
this is what it looks like in my docker compose file:

`redis:`
        `image: bitnami/redis:latest`
        `container_name: dev-redis`
        `working_dir: /bitnami/redis`
        `volumes:`
            `- ./data/redis:/bitnami/redis`
        `environment:`
            `- REDIS_PASSWORD=admin123`
        `ports:`
            `- "6379:6379"`

when i run `docker-compose up`, it gives me this log message
`bitnami    INFO  Initializing redis`
`dev-redis | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis/conf'`

I thought this is a permission issue because base on the update redis now runs as user 1001 so i tried to use `sudo docker-compose up` and it gives me this new error

 `bitnami    INFO  Initializing redis`
`dev-redis | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redis/conf/redis.conf'`

```

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false


```

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 58
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.729GiB
Name: PC10-TINKYWINKY
ID: UG4A:664F:CJQX:U7H3:NEKZ:7N35:AMPL:GYOE:YBKC:BMGO:7EDK:VYKK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

```
docker-compose version 1.11.2, build dfed245
```

**Comment by zed-mob** [comment]
Update:

`volumes:`
            `- ./data/redis:/bitnami`
            `- ./data/redis/conf/redis.conf:/opt/bitnami/redis/conf/redis.conf`

I tried to overwrite the redis config file, using that I've fixed this error
`Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redis/conf/redis.conf'`

but now i have a new one another permission error `Error executing 'postInstallation': EACCES: permission denied, rename '/opt/bitnami/redis/etc' -> '/opt/bitnami/redis/conf/etc'`

also i tried this to set up permissions to redis persistence folder
`sudo chown -R 1001:1001 redis && sudo chmod -R g+rwX redis` I want to know if I'm right about this,

Thank you..

**Comment by javsalgar** [comment]
I was able to reproduce the issue. Try the following workaround. 

```
docker-compose down
rm data/ -R
mkdir -p data/redis
chmod 777 -R data/redis
```

@tompizmor anything to add?

**Comment by n-sviridenko** [comment]
@javsalgar
normally, minikube host-path provisioner puts pvc's into `/tmp/hostpath-provisioner` host path, so in my case I changed chmod to `777` for the `/tmp/hostpath-provisioner/$(kubectl get pvc <pvc name> -o 'jsonpath={.spec.volumeName}'))`.

**Comment by muniyalr** [comment]
Thanks @n-sviridenko tried that still the same error.

W1229 10:20:32.620817   88747 cmd.go:353] log is DEPRECATED and will be removed in a future version. Use logs instead.

```Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing redis
redis   INFO  ==> Validating inputs...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis'```

currently /tmp is a symlink on mac
```lrwxr-xr-x@  1 root  wheel    11 11 Sep 13:38 tmp -> private/tmp```

hence may be permission denied

**Comment by n-sviridenko** [comment]
@muniyalr try to set `777` for the whole `/tmp/hostpath-provisioner` folder.

**Comment by muniyalr** [comment]
even 777 on /tmp/hostpath-provisioner didnt work. Now changed the pv to use a different path and reloaded the pod, i could get redis working.

**Comment by R0binT** [comment]
Hello, I have a similar problem.
When I start my container I get that error :
`Error executing 'postInstallation': Files to substitute resolved to an empty list`

Has anyone an idea about how to fix that ?
Thx

**Comment by javsalgar** [comment]
@R0binT it seems that the error you show is different from the one in this ticket. Could you create a new one filling the template so we have more information about your environment and the steps to reproduce?

**Comment by R0binT** [comment]
@javsalgar yes sure :)
